### ISSUE TITLE
authorizePublish method - TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kareha** [mcollina/aedes#106]
Hi,
when I use this authorizePublish Method

```
aedesInstance.authorizePublish = function (client, packet, callback) {
  var auth = client.user === packet.topic.split('/')[2]
  if (!auth) callback(new Error('no auth'))
  callback(null)
}
```

and then publish a message with an unauthorized/wrong topic:

`mosquitto_pub  -t "/wrongtopic" -m "foo"`

I get this Error at Aedes:

```
/node_modules/fastseries/series.js:92
    if (!err && i < that._list.length) {
                              ^

TypeError: Cannot read property 'length' of null
    at ResultsHolder.release (/node_modules/fastseries/series.js:92:31)
    at Aedes.aedesInstance.authorizePublish (/app.js:91:3)
    at Client.authorizePublish (/node_modules/aedes/lib/handlers/publish.js:44:15)
    at makeCall (/node_modules/fastseries/series.js:113:10)
    at ResultsHolder.release (/node_modules/fastseries/series.js:96:9)
    at Aedes.series [as _series] (/node_modules/fastseries/series.js:39:14)
    at handlePublish (/node_modules/aedes/lib/handlers/publish.js:20:17)
    at handle (/node_modules/aedes/lib/handlers/index.js:27:7)
    at Parser.enqueue (/node_modules/aedes/lib/client.js:253:3)
    at emitOne (events.js:96:13)
```
/app.js:91:3 is here the line with callback(null) in authorizePublish function.

Is that a aedes issue?

**Comment by kareha** [comment]
Sorry, my fault.
Put a **return** infront of **callback(new Error('no auth'))**

Nevermind
