### ISSUE TITLE
QoS 2 PUBREC should not be repeated 

### ISSUE THREAD

**Issue by ckrey** [mcollina/aedes#137]
aedes treats QoS2 different to a lot of other MQTT brokers:

* client sends PUBLISH
* broker replies with PUBREC

... client does not respond to PUBREC with PUBREL within a certain time

* broker repeats PUBREC
* client replies to first PUBREC with PUBREL
* client replies to the second PUBREC with PUBREL
This causes the following error and subsequent disconnect:
```
client error MQTTClient763914 no such packet Error: no such packet
    at MemoryPersistence.incomingGetPacket (/Users/ckrey/node_modules/aedes-persistence/persistence.js:268:11)
    at ClientPacketStatus.pubrelGet (/Users/ckrey/aedes/aedes/lib/handlers/pubrel.js:29:15)
    at makeCall (/Users/ckrey/node_modules/fastseries/series.js:113:10)
    at ResultsHolder.release (/Users/ckrey/node_modules/fastseries/series.js:96:9)
    at Aedes.series [as _series] (/Users/ckrey/node_modules/fastseries/series.js:39:14)
    at handlePubrel (/Users/ckrey/aedes/aedes/lib/handlers/pubrel.js:22:17)
    at handle (/Users/ckrey/aedes/aedes/lib/handlers/index.js:40:7)
    at Parser.enqueue (/Users/ckrey/aedes/aedes/lib/client.js:270:3)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
```

The MQTT spec is not explicit with regards to message repetitions, but other implementations do
not repeat PUBREC after timeout.

The QoS 2 repetitions are handled by the sender:
* If the receiver does not respond with a PUBREC, the PUBLISH message is repeated (with DUP set).
* if the receiver does not respond with a PUBCOMP, the PUBREL message is repeated

**Comment by behrad** [comment]
Hi @ckrey,
Good to see you here man 👍 

It seems you are using default memory persistence.
Can you please confirm the same issue exists with a setup with redis-persistence?

**Comment by ckrey** [comment]
hi @behrad as I am a node novice, I don't see a simple example how to setup aedes with redis-persitence. Maybe you can help out

**Comment by cordovapolymer** [comment]
same issue as I have experienced in earlier versions https://github.com/mcollina/aedes/issues/87
@ckrey,
to use aedes-persistence-redis just [instantiate it ](https://github.com/mcollina/aedes-persistence-redis#api)and pass as an [option to aedes constructor](https://github.com/mcollina/aedes#aedesopts).
Of course you have to setup [redis](https://redis.io/) as well

this should work (compiled from the manuals and yet untested) 
`
var aedesPersistenceRedis = require('aedes-persistence-redis')({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0,
  maxSessionDelivery: 100 // maximum offline messages deliverable on client CONNECT, default is 1000
})
var aedes = require('aedes')({persistence: aedesPersistenceRedis})
var server = require('net').createServer(aedes.handle)
var port = 1883

server.listen(port, function () {
  console.log('server listening on port', port)
})
`

**Comment by ckrey** [comment]
I can confirm, the error occurs with redis persistence too! I don't think it is a persistence error, but a protocol handling problem

```
client error MQTTClient515307 no such packet Error: no such packet
    at decodeBuffer (/Users/ckrey/aedes/aedes-persistence-redis/persistence.js:416:17)
    at tryCatcher (/Users/ckrey/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/ckrey/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/Users/ckrey/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/ckrey/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/ckrey/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/ckrey/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ckrey/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ckrey/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by mcollina** [comment]
I will not have time to work on this, is there anyone that wants to send a PR? I'm ok with the proposed change.

**Comment by behrad** [comment]
I'll try it may be in a week...

**Comment by cordovapolymer** [comment]
@behrad any updates on this?

**Comment by behrad** [comment]
busy these days...

**Comment by tonylin0826** [comment]
Any updates? Or any work around?

**Comment by GavinDmello** [comment]
Hey @ckrey I was looking to reproduce this issue, but could not.
I was using the mqtt-connection library by @mcollina to do this.

Here's my client code

```js
var net = require('net')
var mqttCon = require('mqtt-connection')
var stream = net.createConnection(1883, 'localhost')
var conn = mqttCon(stream)

conn.connect({clean : false, clientId: "ha", protocolVersion : 3})

conn.on('connack', function (packet) {
    console.log("connack received")

    conn.on('pubrec', function(packet) {
      console.log('pubrec')
    })

    conn.publish({ 
      topic : 'hello', 
      qos : 2, 
      payload: 'from', 
      messageId : 1234, 
      retain : false
    }, 
    function() {
      console.log("published")
    })
})
```


As you can see I don't respond with a pubrel to the pubrec. The broker does not seem to respond with a another pubrec if not provided a pubrel in my case.

Could you provide the client code for the same or confirm if this issue is still happening on the latest Aedes version?

**Comment by ckrey** [comment]
I tried the same test case as in July 2017 with aedes@0.36.0

The problem does not occur anymore
