### ISSUE TITLE
aedes-persistence-mongodb throw error

### ISSUE THREAD

**Issue by penglinjiang** [mcollina/aedes#156]
my server.js is as follows:
```
var aedesPersistenceMongoDB = require('aedes-persistence-mongodb');
var persistenceMongo = aedesPersistenceMongoDB({
    url: 'mongodb://127.0.0.1:27017/aedes'
});
var aedes = require('aedes')({
    persistence: persistenceMongo
});
var server = require('net').createServer(aedes.handle);
var port = 1883;

server.listen(port, function () {
    console.log('server listening on port', port);
});

aedes.on('publish', function(packet, client) {
    console.log("published", packet.payload.toString());
});
aedes.on('client', function(client) {
    console.log('client connected', client.id);
});

aedes.on('subscribe', function (subscriptions, client) {
    console.log('client subscribe ', client.id, 'topic is', subscriptions);
})
```
but as long as i run server.js,it get this:
```
server listening on port 1883
/home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'add' of undefined
    at Cursor.<anonymous> (/home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/persistence.js:71:20)
    at emitOne (events.js:115:13)
    at Cursor.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Cursor.Readable.push (_stream_readable.js:195:10)
    at /home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/node_modules/mongodb/lib/cursor.js:1109:10
    at handleCallback (/home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/node_modules/mongodb/lib/utils.js:120:56)
    at /home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/home/duoyi/node_project/node_mqtt/node_modules/aedes-persistence-mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
```

**Comment by GavinDmello** [comment]
@mcollina  Is _matcher and matcher the same instance ?

**Comment by mcollina** [comment]
@GavinDmello https://github.com/mcollina/aedes-cached-persistence/commit/ea2dc99041106e37d4bf07e7116af22dd452dba6#diff-168726dbe96b3ce427e7fedce31bb0bc renamed `_matcher`  to `_trie`. We should just rename the field. Would you mind sending a PR?

**Comment by GavinDmello** [comment]
Oh, It's from aedes-cache
> Would you mind sending a PR?
Sure

**Comment by mcollina** [comment]
Can you please check this again? It should be fixed.
