### ISSUE TITLE
clientError  Cannot parse topic

### ISSUE THREAD

**Issue by muka** [mcollina/aedes#163]
Hi,
I noticed a bunch of such issues in my logs but I cannot find the cause.
This issue come from `mqtt-packet`, the client provided by the callback has no id.

Do you have any suggestion to check for the cause?

```
broker_1      | debug: Error: Cannot parse topic
broker_1      |     at Parser._parsePublish (/app/node_modules/mqtt-packet/parser.js:242:53)
broker_1      |     at Parser._parsePayload (/app/node_modules/mqtt-packet/parser.js:104:14)
broker_1      |     at Parser.parse (/app/node_modules/mqtt-packet/parser.js:37:48)
broker_1      |     at Socket.nextBatch (/app/node_modules/aedes/lib/client.js:61:23)
broker_1      |     at emitNone (events.js:105:13)
broker_1      |     at Socket.emit (events.js:207:7)
broker_1      |     at emitReadable_ (_stream_readable.js:513:10)
broker_1      |     at emitReadable (_stream_readable.js:507:7)
broker_1      |     at addChunk (_stream_readable.js:274:7)
broker_1      |     at readableAddChunk (_stream_readable.js:250:11)
broker_1      |     at Socket.Readable.push (_stream_readable.js:208:10)
broker_1      |     at TCP.onread (net.js:597:20)
```

Thank you

**Comment by mcollina** [comment]
Your client is probably sending malformed CONNECT packets, so it does not have any id.

**Comment by muka** [comment]
Ok will check in this direction! Closing for now
