### ISSUE TITLE
server crashed on a few minutes of high load with Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by ahmadalli** [mcollina/aedes#193]
I've tried to have 2000 users subscribing to 200 channels and publishing on those channels. After a few minutes, the server crashes with ` Maximum call stack size exceeded` error:

```
RangeError: Maximum call stack size exceeded
    at PublishState.ResultsHolder.release (node_modules\fastseries\series.js:99:22)
    at ResultsHolder.release (node_modules\fastseries\series.js:99:22)
    at Aedes.defaultPublished [as published] (node_modules\aedes\aedes.js:312:3)
    at PublishState.callPublished (node_modules\aedes\aedes.js:210:15)
    at makeCall (node_modules\fastseries\series.js:113:10)
    at MQEmitter.ResultsHolder.release (node_modules\fastseries\series.js:96:9)
    at MQEmitter.parallel [as _parallel] (node_modules\fastparallel\parallel.js:25:12)
    at MQEmitter._do (node_modules\mqemitter\mqemitter.js:127:8)
    at released (node_modules\mqemitter\mqemitter.js:61:12)
    at MQEmitter.parallel [as _parallel] (node_modules\fastparallel\parallel.js:26:7)
    at MQEmitter._do (node_modules\mqemitter\mqemitter.js:127:8)
    at released (node_modules\mqemitter\mqemitter.js:61:12)
    at MQEmitter.parallel [as _parallel] (node_modules\fastparallel\parallel.js:26:7)
    at MQEmitter._do (node_modules\mqemitter\mqemitter.js:127:8)
    at released (node_modules\mqemitter\mqemitter.js:61:12)
    at MQEmitter.parallel [as _parallel] (node_modules\fastparallel\parallel.js:26:7)
```
this is my test file: 
[aedes-test.zip](https://github.com/mcollina/aedes/files/1898648/aedes-test.zip)
I run `server.js` first (I have redis up with it's docker image having 2GB memmory `docker run -d -p 6379:6379 redis`)
then I run `high-load.js` and after few minutes (after all users connected and subscribed to channels), hig load test script starts logging `user x reconnecting`  without any success and then server crashes with error written above.

**Comment by ahmadalli** [comment]
also, I observed server memory usage increasing as the time passed. I'm not sure whether it's a memory leak or it's normal. but if I didn't have enough memory, the server would close with this error:
```
<--- Last few GCs --->

[100116:0000016F65E33CD0]   273887 ms: Scavenge 254.2 (320.7) -> 253.7 (323.7) MB, 11.1 / 0.0 ms  allocation failure
[100116:0000016F65E33CD0]   274403 ms: Mark-sweep 255.2 (323.7) -> 254.4 (283.2) MB, 403.8 / 0.0 ms  low memory notification GC in old space requested
[100116:0000016F65E33CD0]   274840 ms: Mark-sweep 254.4 (283.2) -> 254.4 (265.2) MB, 436.6 / 0.0 ms  low memory notification GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: 00007FF69A9E4376
 2: 00007FF69A9E57D0
 3: 00007FF69B028285
 4: 00007FF69B028158
 5: 00007FF69AF1A105
 6: 00007FF69AF18A71
 7: 00007FF69AF185C5
 8: 00007FF69B04F3FC
 9: 00007FF69A920AF4
10: 00007FF69A95C448
11: 00007FF69A959517
12: 00007FF69AA2809F
13: 00007FF69AA3A099
14: 00007FF69AA3AE5B
15: 00007FF69A9EC78E
16: 00007FF69A9ECBDF
17: 00007FF69A9ECF4A
18: 00007FF69B383EF1
19: BaseThreadInitThunk
20: RtlUserThreadStart
```

**Comment by nadalizadeh** [comment]
I have also executed the test on a MacOSX, there seems to be a memory leak somewhere, the server increased the memory with each batch of test clients and finally crashed with the following backtrace:

`<--- Last few GCs --->

[3489:0x102801600]   464142 ms: Mark-sweep 1402.9 (1446.8) -> 1402.9 (1445.8) MB, 2026.1 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2026 ms) last resort 
[3489:0x102801600]   466153 ms: Mark-sweep 1402.9 (1445.8) -> 1402.9 (1445.8) MB, 2011.3 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x161cc74266a1 <JS Object>
    1: new constructor(aka ResultsHolder) [/Users/alin./Downloads/aedes-test/node_modules/fastseries/series.js:~80] [pc=0x2d64795e6616](this=0x5a81d549981 <a ResultsHolder with map 0x3a7128a1ca31>,_release=0x3f9f14182311 <undefined>)
    2: arguments adaptor frame: 0->1
    4: get [/Users/alin./Downloads/aedes-test/node_modules/reusify/reusify.js:~7] [pc=0x2d647956ca75](this=0x11b1ec68fa99 <an ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::internal::Runtime_NewClosure_Tenured(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x2d64790043a7
Abort trap: 6`

**Comment by behrad** [comment]
@ahmadalli Can you run the same test with your server.js configured with mqemitter-redis instead of the default emitter and see if the same happens?

**Comment by ahmadalli** [comment]
@behrad yes. this happens again. see the code: [aedes-test.zip](https://github.com/mcollina/aedes/files/1900511/aedes-test.zip)

this time with this error:
```
server listening on port 1883                                                                               
events.js:165                                                                                               
      throw er; // Unhandled 'error' event                                                                  
      ^                                                                                                     
                                                                                                            
Error: connect ETIMEDOUT                                                                                    
    at Socket.<anonymous> (node_modules\ioredis\lib\redis.js:289:21)             
    at Object.onceWrapper (events.js:272:13)                                                                
    at Socket.emit (events.js:180:13)                                                                       
    at Socket._onTimeout (net.js:396:8)                                                                     
    at ontimeout (timers.js:466:11)                                                                         
    at tryOnTimeout (timers.js:304:5)                                                                       
    at Timer.listOnTimeout (timers.js:267:5)                                                                
Emitted 'error' event at:                                                                                   
    at Redis.<anonymous> (node_modules\mqemitter-redis\mqemitter-redis.js:54:16) 
    at Redis.emit (events.js:180:13)                                                                        
    at Redis.silentEmit (node_modules\ioredis\lib\redis.js:472:22)               
    at node_modules\ioredis\lib\redis\event_handler.js:114:10                    
    at Socket.<anonymous> (node_modules\ioredis\lib\redis.js:293:43)             
    at Object.onceWrapper (events.js:272:13)                                                                
    [... lines matching original stack trace ...]                                                           
    at Timer.listOnTimeout (timers.js:267:5)                           
```

**Comment by behrad** [comment]
> this happens again. see the code: aedes-test.zip

Please post the sample code formatted in github markup, instead of a zip file. Thats makes it easier to move on.

**Comment by ahmadalli** [comment]
this is my server (with redis emitter and redis persistance)
```js
var aedesPersistenceRedis = require("aedes-persistence-redis")
var redis = require('mqemitter-redis')
var mqttOpts = {
    mq: redis({
        port: 6379,
        host: '127.0.0.1',
        db: 4
    }),
    persistence: aedesPersistenceRedis({
        port: 6379, // Redis port
        host: '127.0.0.1', // Redis host
        family: 4, // 4 (IPv4) or 6 (IPv6)
        db: 0,
        maxSessionDelivery: 200, // maximum offline messages deliverable on client CONNECT, default is 1000
        packetTTL: function (packet) { // offline message TTL, default is disabled
            return 15 * 60 //seconds
        }
    })
}

var aedes = require('aedes')(mqttOpts)
var server = require('net').createServer(aedes.handle)
var port = 1883

server.listen(port, function () {
    console.log('server listening on port', port)
})
```

and this is my load-test:
```js
"use strict";

const mqtt = require('mqtt');

const usersCount = 2000;
const usersPergroup = 10;
const userMessagePerSecond = 10;

const userMessageInterval = 1000 / userMessagePerSecond;
const groupsCount = usersCount / usersPergroup;

console.log(`user message interval: ${userMessageInterval}`);
console.log(`count of groups: ${groupsCount}`);

for (var groupId = 0; groupId < groupsCount; groupId++) {
    const groupTopic = `test/group/${groupId}`;
    for (var userId = groupId * usersPergroup; userId < (groupId + 1) * usersPergroup; userId++) {
        runUserClient(userId, groupTopic);
    }
}

function runUserClient(userId, groupTopic) {
    const userClient = mqtt.connect('mqtt://localhost', {
        clientId: `highload-test-${userId}`,
        clean: false
    });

    userClient.on('connect', function () {
        console.log(`user ${userId} connected`);
        userClient.subscribe(groupTopic);
        console.log(`user ${userId} subscribed to group topic ${groupTopic}`);

        var messageNumber = 1;
        setInterval(function () {
            const message = `from ${userId} - ${messageNumber}th message`;
            userClient.publish(groupTopic, message, {
                qos: 0
            });
            messageNumber++;
        }, userMessageInterval);

    });

    userClient.on('reconnect', function () {
        console.log(`user ${userId} reconnecting`);
    });

    userClient.on('offline', function () {
        console.log(`user ${userId} offline`);
    });

    userClient.on('error', function (error) {
        console.log(`user ${userId} client error: ${error}`);
    });

    // userClient.on('message', function (topic, message) {
    //     console.log(`user ${userId} received message: ${message}`);
    // });
}
```

I'll try to fix the redis issue and report back again

**Comment by ahmadalli** [comment]
I'm getting `subscribe scheduled to be closed ASAP for overcoming of output buffer limits.` in redis for the emitter redis while the client type is `Normal` and there's no limitations for normal clients in configs.

**Comment by behrad** [comment]
> subscribe scheduled to be closed ASAP for overcoming of output buffer limits

Are you seeing this in your redis console? Strange!
is that a cloud redis instace or a standalone local one?

**Comment by ahmadalli** [comment]
it's local server

**Comment by behrad** [comment]
> it's my local computer

Check if these helps:

https://stackoverflow.com/questions/32879499/redis-replication-and-client-output-buffer-limit

https://groups.google.com/forum/#!topic/redis-db/LHnNzDU4C-0
