### ISSUE TITLE
Aedes fails retained messages stressMQTT tests

### ISSUE THREAD

**Issue by cefn** [mcollina/aedes#20]
Reporting as requested. Focusing on low numbers of topics for now.

Currently Aedes at https://github.com/mcollina/aedes/commit/2e25a0b4107a8f85bd8844625b8ecb748479faac (installed by softlinking the git repo directly into my project's node_modules folder) is failing to deliver any retained messages at all within the test suite https://github.com/cefn/stressMQTT/

The test "Wildcard subscription of retained messages" reports to the console as follows indicating no messages delivered (javascript arithmetic is ace)! 
```
Timestamp reset
0 Connected
Wildcard subscription of retained messages
1:1 Sent first message
1:0 Sending msg:0
1:0 Sending msg:1
1:0 Sending msg:2
2:1 Sending msg:3
2:0 Sending msg:4
2:0 Sending msg:5
2:0 Sending msg:6
2:0 Sending msg:7
2:0 Sending msg:8
2:0 Sending msg:9
2:0 Sent 10 messages in 1 ms at 0.1ms/msg
37:35 Subscribing
37:0 Subscribed
9978:9941 Sent 10 messages in 9977 ms at 997.7ms/msg
9978:0 Received 0 messages in 1451525952615 ms at Infinity ms/msg
9978:0 Subscribed to 0 topics in 9941 ms at Infinity ms/topic
``` 

If that test is skipped, the third test titled "Individual subscription of retained messages" fails as follows...

```
Timestamp reset
0 Connected
Individual subscription of retained messages
1:1 Sent first message
1:0 Sending msg:0
1:0 Sending msg:1
1:0 Sending msg:2
1:0 Sending msg:3
1:0 Sending msg:4
1:0 Sending msg:5
1:0 Sending msg:6
2:1 Sending msg:7
2:0 Sending msg:8
2:0 Sending msg:9
2:0 Sent 10 messages in 1 ms at 0.1ms/msg
23:21 Subscribing
23:0 Subscribed
23:0 Subscribing to topic:0
23:0 Subscribing to topic:1
24:1 Subscribing to topic:2
24:0 Subscribing to topic:3
24:0 Subscribing to topic:4
24:0 Subscribing to topic:5
24:0 Subscribing to topic:6
24:0 Subscribing to topic:7
24:0 Subscribing to topic:8
24:0 Subscribing to topic:9
24:0 Subscribed to 10 topics in 1 ms at 0.1ms/topic
/Users/cefn/Documents/code/imagination/git/aedes/lib/handlers/index.js:19
    client._keepaliveTimer.reschedule(client._keepaliveInterval)
                          ^

TypeError: Cannot read property 'reschedule' of null
    at handle (/Users/cefn/Documents/code/imagination/git/aedes/lib/handlers/index.js:19:27)
    at Parser.enqueue (/Users/cefn/Documents/code/imagination/git/aedes/lib/client.js:204:3)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser._newPacket (/Users/cefn/Documents/code/imagination/git/aedes/node_modules/mqtt-packet/parser.js:30:10)
    at Parser.parse (/Users/cefn/Documents/code/imagination/git/aedes/node_modules/mqtt-packet/parser.js:42:48)
    at DestroyableTransform.nextBatch (/Users/cefn/Documents/code/imagination/git/aedes/lib/client.js:55:23)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/cefn/Documents/code/imagination/git/stressMQTT/node_modules/readable-stream/lib/_stream_readable.js:464:10)
9970:9946 Sent 10 messages in 9969 ms at 996.9ms/msg
9970:0 Received 0 messages in 1451526399729 ms at Infinity ms/msg
9970:0 Subscribed to 10 topics in 9947 ms at 994.7ms/topic
```

You'll be glad to hear, the fourth test succeeds, though! :)

By contrast, switching the choice of server in the test config header for Mosca or Mosquitto means the same test suite completes with all four as green tests.

**Comment by mcollina** [comment]
All your tests now passes on Aedes 0.12.

**Comment by mcollina** [comment]
That was a really good catch of an edge case I did not though about.
