### ISSUE TITLE
Aedes not properly releasing connections

### ISSUE THREAD

**Issue by JohnCMcDonough** [mcollina/aedes#237]
I've got code where I'm attempting to keep track of the number of clients connected using a prometheus Gauge.

**metrics.ts**
```typescript
  export function clientConnected(projectId: string, ) {
    prom_currentConnections.inc({ ...baseLabelValues, projectId })
  }

  export function clientDisconnected(projectId: string, ) {
    prom_currentConnections.dec({ ...baseLabelValues, projectId })
  }
```
**main.ts**
```typescript
  // projectid is something added to the client during authentication

  aedesInstance.on('client', (client) => {
    metrics.clientConnected(client.projectId);
  })

  aedesInstance.on('clientDisconnect', (client) => {
    metrics.clientDisconnected(client.projectId);
  })
```

the `metrics.clientConnected` and `metrics.clientDisconnected` basically just increment and decrement counters. There is not really any logic here.

If there are socket errors, it seems like the decrement is not always called. After heavy load testing, where all of clients connecting have been shutdown (not always gracefully) we find that this metric sometimes displays that there are clients connected, even when there isn't.

**Comment by mcollina** [comment]
Thanks for reporting, would you like to send a PR with a fix?

**Comment by JohnCMcDonough** [comment]
Sure! 

I’m still trying to diagnose right now. I need a way of getting it to reproduce without having to make thousands of connections. 

I’ll comment with anything else I find.

**Comment by JohnCMcDonough** [comment]
I've been unable to find out what causes it, but I have found that Aedes internally doesn't realize the clients are still connected. I'm not sure if it's because of the long delays in authenticating a client, or if it somehow fails during authentication, or what. But the code below shows that each worker has more connections reported by Aedes than by the TCP Server and WS Server.

```typescript
import aedes from 'aedes';
import net from 'net';
import http from 'http';
import wsStream from 'websocket-stream';
import { aedes_published, aedes_authorize_subscribe, aedes_authorize_publish, aedes_authenticate, AedesExtendedClient } from './broker';

export function startWorker(workerid?: string) {

  const aedesInstance: aedes.Aedes = aedes({
    authenticate: aedes_authenticate,
    authorizePublish: aedes_authorize_publish,
    authorizeSubscribe: aedes_authorize_subscribe,
    published: aedes_published,
    concurrency: 20000,
  });

  setInterval(async () => {
    const tcpConnProm = new Promise<number>((res, rej) => { tcpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    const wsConnProm = new Promise<number>((res, rej) => { httpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    console.log(workerid, aedesInstance['connectedClients'], await tcpConnProm, await wsConnProm)
  }, 5000);

  const tcpServer = net.createServer(aedesInstance.handle)
  const httpServer = http.createServer();
  const websocketServer = wsStream.createServer({ server: httpServer, path: '/mqtt' }, aedesInstance.handle as any);
  var tcpPort = 1883;
  var wsPort = 8883;

  tcpServer.listen(tcpPort, '0.0.0.0', function () {
    console.log(workerid, 'TCP server listening on port', tcpPort)
  })
  httpServer.listen(wsPort, '0.0.0.0', () => {
    console.log(workerid, 'WebSocket server listening on port', wsPort)
  });

}
```

5/13/2019 11:33:04 AM thread-1 19 0 0
5/13/2019 11:33:04 AM thread-2 18 0 0
5/13/2019 11:33:04 AM thread-3 21 0 0
5/13/2019 11:33:04 AM thread-4 20 0 0
5/13/2019 11:33:04 AM thread-5 18 0 0
5/13/2019 11:33:04 AM thread-6 23 0 0
5/13/2019 11:33:04 AM thread-7 17 0 0
5/13/2019 11:33:05 AM thread-8 23 0 0

**Comment by GavinDmello** [comment]
@JohnCMcDonough  Could you check if either one of `clientError`, `connectionError` or `keepaliveTimeout`  events are being fired ?

**Comment by JohnCMcDonough** [comment]
I get clientErrors when they disconnect, but it's just ECONNRESET.

```typescript
//...
  let clientErrorCount = 0
  let connectionErrorCount = 0
  let keepaliveTimeoutCount = 0

  aedesInstance.on('clientError', (c: AedesExtendedClient, e) => {
    clientErrorCount++
    console.log('clientError', e)
  })
  aedesInstance.on('connectionError', (c: AedesExtendedClient, e) => {
    connectionErrorCount++;
    console.log('connectionError', e)
  })

  aedesInstance.on('keepaliveTimeout', (c: AedesExtendedClient) => {
    keepaliveTimeoutCount++;
    console.log('keepaliveTimeout', c.id)
  })

  setInterval(async () => {
    const tcpConnProm = new Promise<number>((res, rej) => { tcpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    const wsConnProm = new Promise<number>((res, rej) => { httpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    console.log(workerid, aedesInstance['connectedClients'], await tcpConnProm, await wsConnProm, clientErrorCount, connectionErrorCount, keepaliveTimeoutCount)
    metrics.setConnectedClients((await tcpConnProm) + (await wsConnProm));
  }, 5000);
//...
```


```
thread-1 29 11 0 77 0 0
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM clientError { Error: read ECONNRESET
5/13/2019 12:41:50 PM at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
5/13/2019 12:41:50 PM thread-5 20 0 0 75 0 0
5/13/2019 12:41:50 PM thread-4 20 0 0 104 0 0
5/13/2019 12:41:50 PM thread-3 22 0 0 51 0 0
5/13/2019 12:41:50 PM thread-6 22 0 0 69 0 0
5/13/2019 12:41:50 PM thread-8 23 0 0 54 0 0
5/13/2019 12:41:50 PM thread-7 19 0 0 77 0 0
5/13/2019 12:41:55 PM thread-2 19 0 0 87 0 0
```

**Comment by JohnCMcDonough** [comment]
The code below appears to reliably create the errors for me. I've removed as much domain specific code as I can.

```typescript
import aedes from 'aedes';
import net from 'net';
import http from 'http';
import wsStream from 'websocket-stream';

function sleep(ms: number) {
  return new Promise(res => setTimeout(res, ms));
}

export function startWorker(workerid?: string) {

  const aedesInstance: aedes.Aedes = aedes({
    // authenticate: aedes_authenticate,
    authenticate: async (client: AedesExtendedClient, username, password, done) => {
      // simulate our network
      await sleep(60 * 1000 * Math.random());
      // simulate an auth failure
      if (Math.random() > 0.9) {
        let aedesError: aedes.AuthenticateError = new Error('A random auth failure occurred') as any;
        aedesError.returnCode = 4; // AuthErrorCode.BAD_USERNAME_OR_PASSWORD
        done(aedesError, false);
      } else {
        done(null, true);
      }
    },
    // authorizePublish: aedes_authorize_publish,
    authorizePublish: async (client, pcket, done) => {
      await sleep(500); // simulate latency writing to persistent store.
      done();
    },
    // authorizeSubscribe: aedes_authorize_subscribe,
    // published: aedes_published,
    concurrency: 20000,
  });

  let clientErrorCount = 0
  let clientsClosed = 0;
  let connectionErrorCount = 0
  let keepaliveTimeoutCount = 0

  aedesInstance.on('clientError', (c: AedesExtendedClient, e) => {
    clientErrorCount++
    console.log('clientError', e)
    c.close(() => {
      console.log('client closed successfully');
      clientsClosed++;
    })
  })
  aedesInstance.on('connectionError', (c: AedesExtendedClient, e) => {
    connectionErrorCount++;
    console.log('connectionError', e)
  })

  aedesInstance.on('keepaliveTimeout', (c: AedesExtendedClient) => {
    keepaliveTimeoutCount++;
    console.log('keepaliveTimeout', c.id)
  })

  setInterval(async () => {
    const tcpConnProm = new Promise<number>((res, rej) => { tcpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    const wsConnProm = new Promise<number>((res, rej) => { httpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    console.log(workerid, JSON.stringify({ brokerClients: aedesInstance['connectedClients'], tcpConn: await tcpConnProm, wsConn: await wsConnProm, clientErrorCount, clientsClosed, connectionErrorCount, keepaliveTimeoutCount }))
  }, 5000);

  const tcpServer = net.createServer(aedesInstance.handle)
  const httpServer = http.createServer();
  const websocketServer = wsStream.createServer({ server: httpServer, path: '/mqtt' }, aedesInstance.handle as any);
  var tcpPort = 1883;
  var wsPort = 8883;

  tcpServer.listen(tcpPort, '0.0.0.0', function () {
    console.log(workerid, 'TCP server listening on port', tcpPort)
  })
  httpServer.listen(wsPort, '0.0.0.0', () => {
    console.log(workerid, 'WebSocket server listening on port', wsPort)
  });

}
```

**Comment by JohnCMcDonough** [comment]
It's for sure some kind of race condition. If I cancel my HTTP requests to authenticate after 10 seconds, and just reject and let the device try again, I don't see any of these issues.

**Comment by gnought** [comment]
Does it relate to https://github.com/mcollina/aedes/pull/243 ?

**Comment by gnought** [comment]
@JohnCMcDonough Thanks for the report and a test. It is reproducible.

To adapt the recent change of type definition. I modified your test for another developers to have a test.

```
import * as aedes from 'aedes';
import * as net from 'net';
import * as http from 'http';
import * as wsStream from 'websocket-stream';

function sleep(ms: number) {
  return new Promise(res => setTimeout(res, ms));
}

export function startWorker(workerid?: string) {

  const aedesInstance: aedes.Aedes = aedes({
    // authenticate: aedes_authenticate,
    authenticate: async (client: aedes.Client, username, password, done) => {
      // simulate our network
      await sleep(60 * 1000 * Math.random());
      // simulate an auth failure
      if (Math.random() > 0.9) {
        let aedesError: aedes.AuthenticateError = new Error('A random auth failure occurred') as any;
        aedesError.returnCode = 4; // AuthErrorCode.BAD_USERNAME_OR_PASSWORD
        done(aedesError, false);
      } else {
        done(null, true);
      }
    },
    // authorizePublish: aedes_authorize_publish,
    authorizePublish: async (client, pcket, done) => {
      await sleep(500); // simulate latency writing to persistent store.
      done();
    },
    // authorizeSubscribe: aedes_authorize_subscribe,
    // published: aedes_published,
    concurrency: 20000,
  });

  let clientErrorCount = 0
  let clientsClosed = 0;
  let connectionErrorCount = 0
  let keepaliveTimeoutCount = 0

  aedesInstance.on('clientError', (c: aedes.Client, e) => {
    clientErrorCount++
    console.log('clientError', e)
    c.close(() => {
      console.log('client closed successfully');
      clientsClosed++;
    })
  })
  aedesInstance.on('connectionError', (c: aedes.Client, e) => {
    connectionErrorCount++;
    console.log('connectionError', e)
  })

  aedesInstance.on('keepaliveTimeout', (c: aedes.Client) => {
    keepaliveTimeoutCount++;
    console.log('keepaliveTimeout', c.id)
  })

  setInterval(async () => {
    const tcpConnProm = new Promise<number>((res, rej) => { tcpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    const wsConnProm = new Promise<number>((res, rej) => { httpServer.getConnections((err, count) => { err ? rej(err) : res(count) }); })
    console.log(workerid, JSON.stringify({ brokerClients: aedesInstance['connectedClients'], tcpConn: await tcpConnProm, wsConn: await wsConnProm, clientErrorCount, clientsClosed, connectionErrorCount, keepaliveTimeoutCount }))
  }, 5000);

  const tcpServer = net.createServer(aedesInstance.handle)
  const httpServer = http.createServer();
  const websocketServer = wsStream.createServer({ server: httpServer, path: '/mqtt' }, aedesInstance.handle as any);
  var tcpPort = 1883;
  var wsPort = 8883;

  tcpServer.listen(tcpPort, '0.0.0.0', function () {
    console.log(workerid, 'TCP server listening on port', tcpPort)
  })
  httpServer.listen(wsPort, '0.0.0.0', () => {
    console.log(workerid, 'WebSocket server listening on port', wsPort)
  });

}

startWorker("test")
```

**Comment by gnought** [comment]
Fixed in https://github.com/mcollina/aedes/pull/283
