### ISSUE TITLE
Test fails: test/meta.js

### ISSUE THREAD

**Issue by robertsLando** [mcollina/aedes#339]
I have just try to run all tests and the test and this is the output: 

```bash
...
⨯ count connected clients
  not ok 333 one connected clients
    ---
      operator: equal
      expected: 1
      actual:   2
      at: <anonymous> (/aedes/test/meta.js:30:11)
      stack: |-
        Error: one connected clients
            at Test.assert [as _assert] (/aedes/node_modules/tape/lib/test.js:225:54)
            at Test.bound [as _assert] (/aedes/node_modules/tape/lib/test.js:77:32)
            at Test.equal (/aedes/node_modules/tape/lib/test.js:385:10)
            at Test.bound [as equal] (/aedes/node_modules/tape/lib/test.js:77:32)
            at /aedes/test/meta.js:30:11
            at _combinedTickCallback (internal/process/next_tick.js:132:7)
            at process._tickCallback (internal/process/next_tick.js:181:9)
    ...

# tests 683
# pass  682
⨯ fail  1
```

**Comment by gnought** [comment]
Has been fixed on https://github.com/mcollina/aedes/pull/340
