### ISSUE TITLE
TypeError when using mqemitter-mongodb

### ISSUE THREAD

**Issue by kareha** [mcollina/aedes#92]
I get an Error every time I publish a message with Aedes, and answer from client to the same topic:

```
/mqtt-test/node_modules/mqemitter-mongodb/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:648:11)
    at publish (/mqtt-test/node_modules/aedes/node_modules/mqtt-packet/writeToStream.js:258:17)
    at Object.generate [as writeToStream] (/mqtt-test/node_modules/aedes/node_modules/mqtt-packet/writeToStream.js:21:14)
    at write (/mqtt-test/node_modules/aedes/lib/write.js:6:21)
    at writeQoS (/mqtt-test/node_modules/aedes/lib/client.js:135:5)
    at MQEmitterMongoDB.deliverQoS (/mqtt-test/node_modules/aedes/lib/client.js:107:11)
    at goNoResultsArray (/mqtt-test/node_modules/fastparallel/parallel.js:111:18)
    at MQEmitterMongoDB.parallel [as _parallel] (/mqtt-test/node_modules/fastparallel/parallel.js:35:9)
    at MQEmitterMongoDB.MQEmitter._do (/mqtt-test/node_modules/mqemitter/mqemitter.js:127:8)
    at MQEmitterMongoDB.emit (/mqtt-test/node_modules/mqemitter/mqemitter.js:110:10)
```

My Aedes Broker:

```
var aedes = require('aedes')
var mqemitter = require('mqemitter-mongodb')

var mq = mqemitter({
  url: 'mongodb://localhost:27017/mqemitter'
})

aedesInstance = aedes({ mq: mq });

var server = require('net').createServer(aedesInstance.handle)
var port = 1884

server.listen(port, function () {
  console.log('server listening on port', port)
})

setInterval(function() {
  var message = {
    cmd: 'publish',
    qos: 2,
    topic: '/node/test',
    payload: 'Hello',
    retain: false
  };
  aedesInstance.publish(message, function() {
    console.log('Said Hello ');
  });
}, 2000);
```

My Client:

```
var mqtt = require('mqtt');
var client  = mqtt.connect('mqtt://localhost:1884', { clean: true });

client.on('connect', function () {

  client.subscribe('/node/test', {qos: 2}, function(err, granted) {
    console.log('granted: ', granted);
  });
})

client.on('message', function (topic, message) {

  if (message.toString() === 'Hello') {
    client.publish('/node/test', 'Hi back', {qos:2}, function(){})
  }
})
```

Any idea what I'm doing wrong here? :) Thx

**Comment by GavinDmello** [comment]
@kareha Thanks for reporting this.
This is bug in mqemitter-mongodb

**Comment by kareha** [comment]
Ok, thank you. Should I open an issue at mqemitter-mongodb?
Since it is the same developer :)

**Comment by mcollina** [comment]
See https://github.com/mcollina/mqemitter-mongodb/pull/4.

Very happy for any contributions really! I'll have an hard time contributing till next week.

**Comment by kareha** [comment]
Thank you very much for quick response :)
You can close this issue here then.

**Comment by mcollina** [comment]
All of that is released, thanks to @GavinDmello!
